# Generated by Django 4.2.21 on 2026-08-27 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10)),
                ('default_mode', models.CharField(default='auto', max_length=20)),
                ('enter_to_send', models.BooleanField(default=True)),
                ('show_suggested_prompts', models.BooleanField(default=True)),
                ('auto_scroll', models.BooleanField(default=True)),
                ('confirm_delete', models.BooleanField(default=True)),
                ('theme', models.CharField(default='system', max_length=10)),
                ('chat_density', models.CharField(default='comfortable', max_length=10)),
                ('animations', models.BooleanField(default=True)),
                ('reduce_motion', models.BooleanField(default=False)),
                ('font_size', models.CharField(default='medium', max_length=10)),
                ('voice_enabled', models.BooleanField(default=True)),
                ('voice_id', models.CharField(default='vision-male', max_length=50)),
                ('speech_speed', models.CharField(default='1x', max_length=10)),
                ('autoplay_voice', models.BooleanField(default=False)),
                ('chat_model', models.CharField(blank=True, default='', max_length=100)),
                ('code_model', models.CharField(blank=True, default='', max_length=100)),
                ('vision_model', models.CharField(blank=True, default='', max_length=100)),
                ('reasoning_model', models.CharField(blank=True, default='', max_length=100)),
                ('agent_model', models.CharField(blank=True, default='', max_length=100)),
                ('temperature', models.FloatField(default=0.2)),
                ('context_length', models.IntegerField(default=8192)),
                ('streaming', models.BooleanField(default=True)),
                ('show_generation_status', models.BooleanField(default=True)),
                ('fast_mode', models.BooleanField(default=True)),
                ('use_routing', models.BooleanField(default=True)),
                ('keep_warm', models.BooleanField(default=True)),
                ('max_tokens', models.IntegerField(default=2048)),
                ('chat_history_enabled', models.BooleanField(default=True)),
                ('memory_enabled', models.BooleanField(default=True)),
                ('save_files', models.BooleanField(default=True)),
                ('use_history_context', models.BooleanField(default=True)),
                ('analytics', models.BooleanField(default=False)),
                ('personalization', models.BooleanField(default=True)),
                ('notif_ai_complete', models.BooleanField(default=True)),
                ('notif_agent_complete', models.BooleanField(default=True)),
                ('notif_build_complete', models.BooleanField(default=True)),
                ('notif_research_complete', models.BooleanField(default=True)),
                ('notif_system', models.BooleanField(default=True)),
                ('notif_email', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
