# Generated by Django 4.2.21 on 2026-08-25 17:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(help_text='Concise LLM-generated summary (≤ 200 words)')),
                ('content', models.TextField(help_text='Full source content (stored for re-processing)')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 of stripped content — deduplication key', max_length=64, unique=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('authority_score', models.PositiveSmallIntegerField(default=50)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('web_dev', 'Web Development'), ('databases', 'Databases'), ('ai_ml', 'AI & Machine Learning'), ('security', 'Security'), ('devops', 'DevOps & Cloud'), ('technology', 'Technology News'), ('science', 'Science'), ('general', 'General')], default='general', max_length=50)),
                ('subcategory', models.CharField(blank=True, help_text="e.g. 'JavaScript', 'React', 'PostgreSQL'", max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('quality_score', models.PositiveSmallIntegerField(default=0, help_text='Composite 0–100 score')),
                ('relevance_score', models.PositiveSmallIntegerField(default=0)),
                ('freshness_score', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded by newer'), ('rejected', 'Rejected'), ('pending', 'Pending admin approval'), ('conflict', 'Conflicting sources')], db_index=True, default='active', max_length=20)),
                ('conflict_note', models.TextField(blank=True, help_text='Describes any contradicting information found')),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, help_text="e.g. 'React 18.3.0'", max_length=50)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('admin_approved', models.BooleanField(default=True, help_text='False until admin approves pending items')),
            ],
            options={
                'verbose_name': 'Knowledge Item',
                'ordering': ['-quality_score', '-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('source_type', models.CharField(choices=[('rss', 'RSS Feed'), ('url', 'URL / Documentation'), ('admin_paste', 'Admin Paste'), ('admin_file', 'Admin File Upload')], default='url', max_length=20)),
                ('authority_tier', models.CharField(choices=[('official', 'Official (Tier 1)'), ('reputable', 'Reputable Publication (Tier 2)'), ('community', 'Community / Blog (Tier 3)'), ('unknown', 'Unknown')], default='community', max_length=20)),
                ('authority_score', models.PositiveSmallIntegerField(default=50, help_text='0–100. Official docs ≈ 95, reputable press ≈ 75, blogs ≈ 50.')),
                ('category', models.CharField(default='general', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('fetch_interval_hours', models.PositiveSmallIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Knowledge Source',
                'ordering': ['-authority_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_by', models.CharField(choices=[('scheduler', 'Scheduler'), ('admin', 'Admin'), ('api', 'API')], default='scheduler', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial (some errors)')], db_index=True, default='running', max_length=20)),
                ('sources_processed', models.PositiveIntegerField(default=0)),
                ('documents_fetched', models.PositiveIntegerField(default=0)),
                ('items_added', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('items_rejected', models.PositiveIntegerField(default=0)),
                ('duplicates_skipped', models.PositiveIntegerField(default=0)),
                ('conflicts_detected', models.PositiveIntegerField(default=0)),
                ('category_breakdown', models.JSONField(blank=True, default=dict)),
                ('benchmark_results', models.JSONField(blank=True, null=True)),
                ('previous_benchmark', models.JSONField(blank=True, null=True)),
                ('benchmark_regression', models.BooleanField(default=False)),
                ('error_log', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Learning Run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('manual', 'Manual only'), ('disabled', 'Disabled')], default='daily', max_length=10)),
                ('schedule_hour', models.PositiveSmallIntegerField(default=2, help_text='UTC hour for daily run (0–23)')),
                ('schedule_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of week for weekly (0=Mon)', null=True)),
                ('news_enabled', models.BooleanField(default=True)),
                ('technology_enabled', models.BooleanField(default=True)),
                ('coding_enabled', models.BooleanField(default=True)),
                ('security_enabled', models.BooleanField(default=True)),
                ('ai_ml_enabled', models.BooleanField(default=True)),
                ('min_quality_score', models.PositiveSmallIntegerField(default=60)),
                ('auto_approve', models.BooleanField(default=True, help_text='Automatically approve items above quality threshold')),
                ('auto_finetune_enabled', models.BooleanField(default=False)),
                ('reject_on_benchmark_regression', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning Settings',
                'verbose_name_plural': 'Learning Settings',
            },
        ),
        migrations.CreateModel(
            name='LearningNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.knowledgeitem')),
                ('learning_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='learning.learningrun')),
            ],
            options={
                'verbose_name': 'Learning Notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='learning_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='learning.learningrun'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='learning.knowledgesource'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='learning.knowledgeitem'),
        ),
        migrations.CreateModel(
            name='AdminTrainingExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(help_text='Example user request / question')),
                ('answer', models.TextField(help_text='Ideal answer or code')),
                ('quality', models.CharField(choices=[('good', 'Good (preferred)'), ('bad', 'Bad (anti-pattern)'), ('neutral', 'Neutral')], default='good', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Why is this a good / bad answer?')),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('web_dev', 'Web Development'), ('databases', 'Databases'), ('ai_ml', 'AI & Machine Learning'), ('security', 'Security'), ('devops', 'DevOps & Cloud'), ('technology', 'Technology News'), ('science', 'Science'), ('general', 'General')], default='programming', max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source_description', models.CharField(default='Admin upload', max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('preview_summary', models.TextField(blank=True, help_text='Auto-generated preview shown before approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_example', to='learning.knowledgeitem')),
            ],
            options={
                'verbose_name': 'Admin Training Example',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['status', 'category'], name='learning_kn_status_a4e67c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['status', 'quality_score'], name='learning_kn_status_353768_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['category', 'collected_at'], name='learning_kn_categor_70e046_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['content_hash'], name='learning_kn_content_223ee8_idx'),
        ),
    ]
