# Generated by Django 4.2.21 on 2026-08-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='ttft_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
