# Generated by Django 5.2.17 on 2026-08-24 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0004_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('preference', 'Preference'), ('project', 'Project'), ('fact', 'Fact'), ('instruction', 'Instruction')], db_index=True, default='fact', max_length=20)),
                ('content', models.TextField(help_text='What VISION remembers')),
                ('importance', models.PositiveSmallIntegerField(default=1, help_text='1-5, higher = surfaced first')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned memories are always injected')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_sources', to='ai_agent.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Memories',
                'ordering': ['-is_pinned', '-importance', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='ai_agent_me_user_id_833638_idx'), models.Index(fields=['user', 'is_pinned'], name='ai_agent_me_user_id_0810c6_idx'), models.Index(fields=['user', 'updated_at'], name='ai_agent_me_user_id_8eacf0_idx')],
            },
        ),
    ]
